language: python
python:
  - 3.5
install:
  - pip install coverage
  - pip install colorize
  - pip install python-coveralls
script:
  - coverage run -m unittest
  - coverage report -m
  - python -m colorize -h
after_success:
  - coveralls
