language: python
python:
  - 3.5
install:
  - pip install coverage
  - pip install python-coveralls
  - pip install colorama
script:
  - coverage run -m unittest
  - coverage report -m
after_success:
  - coveralls
